[2024-08-11T20:16:45.604+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T20:16:45.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_migration.weather_data_migration manual__2024-08-11T20:16:44.525122+00:00 [queued]>
[2024-08-11T20:16:45.625+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_migration.weather_data_migration manual__2024-08-11T20:16:44.525122+00:00 [queued]>
[2024-08-11T20:16:45.625+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-11T20:16:45.630+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): weather_data_migration> on 2024-08-11 20:16:44.525122+00:00
[2024-08-11T20:16:45.635+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=266) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-11T20:16:45.636+0000] {standard_task_runner.py:64} INFO - Started process 268 to run task
[2024-08-11T20:16:45.636+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_migration', 'weather_data_migration', 'manual__2024-08-11T20:16:44.525122+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_migration_dag.py', '--cfg-path', '/tmp/tmptglsvvqq']
[2024-08-11T20:16:45.637+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask weather_data_migration
[2024-08-11T20:16:45.657+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_migration.weather_data_migration manual__2024-08-11T20:16:44.525122+00:00 [running]> on host 032430a33e2d
[2024-08-11T20:16:45.691+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_migration' AIRFLOW_CTX_TASK_ID='weather_data_migration' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T20:16:44.525122+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-11T20:16:44.525122+00:00'
[2024-08-11T20:16:45.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T20:16:45.693+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-11T20:16:45.694+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/weather_data_migration.py --connection postgresql+psycopg2://***:***@postgres/***']
[2024-08-11T20:16:45.699+0000] {subprocess.py:86} INFO - Output:
[2024-08-11T20:16:46.110+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-11T20:16:46.110+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T20:16:46.120+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_migration, task_id=weather_data_migration, run_id=manual__2024-08-11T20:16:44.525122+00:00, execution_date=20240811T201644, start_date=20240811T201645, end_date=20240811T201646
[2024-08-11T20:16:46.154+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-11T20:16:46.161+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-11T20:16:46.161+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
