[2024-08-11T20:25:25.139+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T20:25:25.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather.import_weather_data_to_csv manual__2024-08-11T20:25:23.919589+00:00 [queued]>
[2024-08-11T20:25:25.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather.import_weather_data_to_csv manual__2024-08-11T20:25:23.919589+00:00 [queued]>
[2024-08-11T20:25:25.153+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-11T20:25:25.158+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): import_weather_data_to_csv> on 2024-08-11 20:25:23.919589+00:00
[2024-08-11T20:25:25.163+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=388) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-11T20:25:25.164+0000] {standard_task_runner.py:64} INFO - Started process 390 to run task
[2024-08-11T20:25:25.164+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather', 'import_weather_data_to_csv', 'manual__2024-08-11T20:25:23.919589+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpib_n5dne']
[2024-08-11T20:25:25.167+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask import_weather_data_to_csv
[2024-08-11T20:25:25.207+0000] {task_command.py:426} INFO - Running <TaskInstance: weather.import_weather_data_to_csv manual__2024-08-11T20:25:23.919589+00:00 [running]> on host 032430a33e2d
[2024-08-11T20:25:25.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather' AIRFLOW_CTX_TASK_ID='import_weather_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T20:25:23.919589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-11T20:25:23.919589+00:00'
[2024-08-11T20:25:25.243+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T20:25:25.244+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-11T20:25:25.244+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/weather_data_ingestion_2.py --date 2024-08-11']
[2024-08-11T20:25:25.250+0000] {subprocess.py:86} INFO - Output:
[2024-08-11T20:25:27.653+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-11T20:25:27.656+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T20:25:27.674+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather, task_id=import_weather_data_to_csv, run_id=manual__2024-08-11T20:25:23.919589+00:00, execution_date=20240811T202523, start_date=20240811T202525, end_date=20240811T202527
[2024-08-11T20:25:27.707+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-11T20:25:27.728+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-11T20:25:27.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
