[2024-08-12T17:36:32.090+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T17:36:32.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_table_drop.weather_data_table_drop manual__2024-08-12T17:36:30.074131+00:00 [queued]>
[2024-08-12T17:36:32.110+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_table_drop.weather_data_table_drop manual__2024-08-12T17:36:30.074131+00:00 [queued]>
[2024-08-12T17:36:32.111+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-12T17:36:32.117+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): weather_data_table_drop> on 2024-08-12 17:36:30.074131+00:00
[2024-08-12T17:36:32.130+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4762) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-12T17:36:32.134+0000] {standard_task_runner.py:64} INFO - Started process 4764 to run task
[2024-08-12T17:36:32.133+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_table_drop', 'weather_data_table_drop', 'manual__2024-08-12T17:36:30.074131+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/delete_openmeteo_dag.py', '--cfg-path', '/tmp/tmpd4r19xbi']
[2024-08-12T17:36:32.138+0000] {standard_task_runner.py:91} INFO - Job 167: Subtask weather_data_table_drop
[2024-08-12T17:36:32.217+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_table_drop.weather_data_table_drop manual__2024-08-12T17:36:30.074131+00:00 [running]> on host b0294fd9f5f9
[2024-08-12T17:36:32.276+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_table_drop' AIRFLOW_CTX_TASK_ID='weather_data_table_drop' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T17:36:30.074131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T17:36:30.074131+00:00'
[2024-08-12T17:36:32.278+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T17:36:32.279+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-12T17:36:32.279+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/delete_table.py --connection postgresql+psycopg2://***:***@postgres/***']
[2024-08-12T17:36:32.287+0000] {subprocess.py:86} INFO - Output:
[2024-08-12T17:36:32.858+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-12T17:36:32.859+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T17:36:32.882+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_table_drop, task_id=weather_data_table_drop, run_id=manual__2024-08-12T17:36:30.074131+00:00, execution_date=20240812T173630, start_date=20240812T173632, end_date=20240812T173632
[2024-08-12T17:36:32.907+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-12T17:36:32.922+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T17:36:32.923+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
