[2024-08-12T06:04:23.971+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T06:04:23.980+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather.export_data_to_db scheduled__2024-08-12T04:58:00+00:00 [queued]>
[2024-08-12T06:04:23.983+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather.export_data_to_db scheduled__2024-08-12T04:58:00+00:00 [queued]>
[2024-08-12T06:04:23.983+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-12T06:04:23.992+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-08-12 04:58:00+00:00
[2024-08-12T06:04:23.996+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1946) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-12T06:04:23.997+0000] {standard_task_runner.py:64} INFO - Started process 1948 to run task
[2024-08-12T06:04:23.997+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather', 'export_data_to_db', 'scheduled__2024-08-12T04:58:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp96528gdv']
[2024-08-12T06:04:23.998+0000] {standard_task_runner.py:91} INFO - Job 142: Subtask export_data_to_db
[2024-08-12T06:04:24.022+0000] {task_command.py:426} INFO - Running <TaskInstance: weather.export_data_to_db scheduled__2024-08-12T04:58:00+00:00 [running]> on host b0294fd9f5f9
[2024-08-12T06:04:24.053+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T04:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-12T04:58:00+00:00'
[2024-08-12T06:04:24.054+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T06:04:24.055+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-12T06:04:24.055+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/weather_to_db.py --date 2024-08-12 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-08-12T06:04:24.068+0000] {subprocess.py:86} INFO - Output:
[2024-08-12T06:04:24.681+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-12T06:04:24.682+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T06:04:24.692+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather, task_id=export_data_to_db, run_id=scheduled__2024-08-12T04:58:00+00:00, execution_date=20240812T045800, start_date=20240812T060423, end_date=20240812T060424
[2024-08-12T06:04:24.724+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-12T06:04:24.731+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T06:04:24.731+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
